import { mkdir, writeFile } from "node:fs/promises";
import { compileDefinitions, staticFilterId } from "../dist/compiler.js";
import { recipes } from "../dist/catalog.js";
import { resolveGeneratedAt } from "./reproducible-time.mjs";

const output = new URL("../generated/", import.meta.url);
await mkdir(output, { recursive: true });
const selections = [];
for (const recipe of recipes) {
  selections.push({ recipe: recipe.id });
  for (const preset of Object.keys(recipe.presets)) selections.push({ recipe: recipe.id, preset });
}
const definitions = compileDefinitions(recipes, selections);
await writeFile(new URL("definitions.svg", output), definitions + "\n");

const registry = {
  schema: "melodicbloom.svg-filter-registry/0.1",
  version: "0.1.0",
  generatedAt: resolveGeneratedAt(process.env.SOURCE_DATE_EPOCH),
  recipeCount: recipes.length,
  presetCount: recipes.reduce((sum, recipe) => sum + Object.keys(recipe.presets).length, 0),
  recipes: recipes.map((recipe) => ({
    id: recipe.id,
    name: recipe.name,
    version: recipe.version,
    status: recipe.status,
    family: recipe.family,
    intent: recipe.intent,
    tags: recipe.tags,
    parameters: recipe.parameters,
    presets: Object.fromEntries(Object.entries(recipe.presets).map(([key, value]) => [key, {
      ...value,
      filterId: staticFilterId(recipe.id, key),
      filterUrl: `url("#${staticFilterId(recipe.id, key)}")`,
    }])),
    baseFilterId: staticFilterId(recipe.id),
    performance: recipe.performance,
    accessibility: recipe.accessibility,
    governance: recipe.governance,
  })),
};
await writeFile(new URL("registry.json", output), JSON.stringify(registry, null, 2) + "\n");

const css = recipes.flatMap((recipe) => Object.keys(recipe.presets).map((preset) =>
  `.mb-filter--${recipe.id}--${preset}{filter:url("#${staticFilterId(recipe.id, preset)}");}`
)).join("\n");
await writeFile(new URL("presets.css", output), `/* Generated by @melodicbloom/svg-filter-atlas */\n${css}\n`);
console.log(`Generated ${selections.length} filters, registry.json, and presets.css.`);
